spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MasterNomad/EPAM_lab_spring_cloud_config

#  profiles:
#    active: native

server:
  port: ${CONFIG_PORT:8888}